[changelog]
# 生成的变更日志文件名（默认：CHANGELOG.md）
file = "CHANGELOG.md"
# 是否覆盖已存在的文件（默认：true）
overwrite = true
# 生成日志的提交范围（如 "HEAD.." 表示最新提交）
commit_range = "HEAD.."
# 日志头部内容（支持多行字符串）
header = """
# Changelog\n
All notable changes to this project will be documented here.\n
"""
# 日志条目排序方式（可选值：asc, desc）
sorting = "desc"

# 标签匹配规则
[tag]
# 匹配 Git 标签的正则表达式（如 v1.0.0）
regex = "^v(?P<version>.+)$"
# 跳过的标签（如 alpha/beta 版本）
skip_tags = ["v0.1.0-beta"]
# 标签日期格式（默认：%Y-%m-%d）
date_format = "%Y-%m-%d"
# 标签排序方式（默认按版本号排序）
sorting = "semver"